replicaCount: 1

image:
  repository: pro.registry.gitlab.metadata.dev.cf-deployments.org/base-infrastructure/docker-registry/cf-voting-app
  tag: latest
  pullPolicy: Always

imagePullSecrets: []
nameOverride: ""
fullnameOverride: ""

service:
  type: ClusterIP
  port: 9091

ingress:
  enabled: true
  disableActuatorEndpoint: true
  additionalDomains: []

resources: {}
  # limits:
  #   cpu: 100m
  #   memory: 128Mi
  # requests:
  #   cpu: 100m
  #   memory: 128Mi

nodeSelector: {}

monitoring:
  enabled: true
  alerting:
    enabled: true

diagnosticMode:
  enabled: false

ledgerFollowerAppUrl: http://cf-cardano-ballot-ledger-follower-api-voting-ledger-follower-ap:9090
corsAllowedOrigins: https://{{ .Values.domain }}
springProfiles: dev--preprod
useJwt: false
leaderboardForceResults: "false"

yaci:
  startBlockHash: ca71d7941c316561c3b21d0f557f34d97a61f97a333c18ed5f2800d74b64e377
  startSlotNumber: "32349482"
