stage: pro

network: mainnet

domain: pro.cf-cip1694-mainnet.eu-west-1.1694ballot.cardano.org

namespace: cf-cip1694

cf-cardano-ballot-infra:
  enabled: true
  postgresql:
    enabled: false

cf-cardano-ballot-ui:
  enabled: true
  values:
    image:
      tag: 0.2.75
    votingAppServerUrl: "https://api.1694ballot.cardano.org"
    votingLedgerFollowerAppServerUrl: "https://follower-api.1694ballot.cardano.org"
    votingVerificationAppServerUrl: "https://verification-api.1694ballot.cardano.org"
    eventId: "CIP-1694_Pre_Ratification_TEST_2"
    categoryId: "CIP-1694_Pre_Ratification_TEST_2"
    googleGormUrl: "https://docs.google.com/forms/u/0/d/e/1FAIpQLSe-dSU0-bi8bjk0wiOaRXj02nxYLvgnpKBgc-eYGRpPYO-y5Q"
    googleFormVoteContextInputName: "entry.75173622"
    ingress:
      additionalDomains:
        - 1694ballot.cardano.org

cf-cardano-ballot-voting-api:
  enabled: true
  values:
    image:
      tag: 0.2.75
    monitoring:
      alerting:
        enabled: false
    leaderboardForceResults: "true"
    corsAllowedOrigins: https://{{ .Values.domain }},https://1694ballot.cardano.org,http://localhost:3000
    ingress:
      additionalDomains:
        - api.1694ballot.cardano.org

cf-cardano-ballot-verification-api:
  enabled: true
  values:
    image:
      tag: 0.2.75
    corsAllowedOrigins: https://{{ .Values.domain }},https://1694ballot.cardano.org,http://localhost:3000
    ingress:
      additionalDomains:
        - verification-api.1694ballot.cardano.org

cf-cardano-ballot-ledger-follower-api:
  enabled: true
  values:
    image:
      tag: 0.2.75
    bindOnEventIds: CIP-1694_Pre_Ratification_TEST_2
    yaci:
      startBlockHash: 5fbd74e502832d31301b3473117cb99d162b3b0fc149656391f806170c93e1c0
      startSlotNumber: "106876819"
    instances:
      - name: follower-1
        enabled: true
        schemaName: follower_1
      - name: follower-2
        enabled: true
        schemaName: follower_2
    corsAllowedOrigins: https://{{ .Values.domain }},https://1694ballot.cardano.org.org,http://localhost:3000
    ingress:
      additionalDomains:
        - follower-api.1694ballot.cardano.org

cf-voting-verification-ui:
  values:
    image:
      tag: 0.2.75

cf-vote-commitment:
  values:
    image:
      tag: 0.2.75
    instances:
      - name: active-hour
        voteCommitmentCronExpression: "0 0 * * * *"
      - name: active-half-hour
        voteCommitmentCronExpression: "0 30 * * * *"
    ledgerFollowerAppUrl: http://cf-cardano-ballot-ledger-follower-api-voting-ledger-follower-ap:9090
