stage: perf

network: preprod

domain: perf.cf-cip1694-perf.eu-west-1.metadata.dev.cf-deployments.org

namespace: cf-cip1694

cf-cardano-ballot-infra:
  enabled: true

cf-cardano-ballot-ui:
  enabled: true
  values:
    image:
      tag: 0.2.74
    votingAppServerUrl: "https://api.{{ .Values.domain }}"
    votingLedgerFollowerAppServerUrl: "https://follower-api.{{ .Values.domain }}"
    votingVerificationAppServerUrl: "https://verification-api.{{ .Values.domain }}"
    eventId: "CIP-1694_Pre_Ratification_PER1"
    categoryId: "CIP-1694_Pre_Ratification_PER1"
    googleGormUrl: "https://docs.google.com/forms/u/0/d/e/1FAIpQLSe-dSU0-bi8bjk0wiOaRXj02nxYLvgnpKBgc-eYGRpPYO-y5Q"
    googleFormVoteContextInputName: "entry.75173622"

cf-cardano-ballot-voting-api:
  enabled: true
  values:
    image:
      tag: v0.2.70-2-g51b6485d
    monitoring:
      alerting:
        enabled: false
    leaderboardForceResults: "true"

cf-cardano-ballot-verification-api:
  enabled: true
  values:
    image:
      tag: 0.2.74

cf-cardano-ballot-ledger-follower-api:
  enabled: true
  values:
    image:
      tag: v0.2.70-2-g51b6485d
    bindOnEventIds: CIP-1694_Pre_Ratification_PER1
    yaci:
      startBlockHash: ad03698d53d72b86b40c7747ffd5a960fbb3a71ac2f1189169e9d315449c24dc
      startSlotNumber: "41558438"
    corsAllowedOrigins: https://{{ .Values.domain }},http://localhost:3000
    instances:
      - name: follower-1
        enabled: true
        schemaName: follower_1
      - name: follower-2
        enabled: true
        schemaName: follower_2

cf-voting-verification-ui:
  values:
    image:
      tag: 0.2.74

cf-vote-commitment:
  values:
    image:
      tag: 0.2.74
    instances:
      - name: active-hour
        voteCommitmentCronExpression: "0 0 * * * *"
      - name: active-half-hour
        voteCommitmentCronExpression: "0 30 * * * *"
    ledgerFollowerAppUrl: http://cf-cardano-ballot-ledger-follower-api-voting-ledger-follower-ap:9090
