stage: stg

network: main

domain: stg.cf-cip1694-preprod.eu-west-1.metadata.dev.cf-deployments.org

cf-cardano-ballot-infra:
  enabled: true

cf-cardano-ballot-ui:
  enabled: true
  values:
    image:
      tag: 0.2.75-2-ebac8
    votingAppServerUrl: "https://api.cip1694.metadata.dev.cf-deployments.org"
    votingLedgerFollowerAppServerUrl: "https://follower-api.cip1694.metadata.dev.cf-deployments.org"
    votingVerificationAppServerUrl: "https://verification-api.cip1694.metadata.dev.cf-deployments.org"
    eventId: "CIP-1694_Pre_Ratification_TEST_2"
    categoryId: "CIP-1694_Pre_Ratification_TEST_2"
    googleGormUrl: "https://docs.google.com/forms/u/0/d/e/1FAIpQLSe-dSU0-bi8bjk0wiOaRXj02nxYLvgnpKBgc-eYGRpPYO-y5Q"
    googleFormVoteContextInputName: "entry.75173622"
    ingress:
      additionalDomains:
        - cip1694.metadata.dev.cf-deployments.org

cf-cardano-ballot-voting-api:
  enabled: true
  values:
    springProfiles: prod
    useJwt: true
    image:
      tag: 0.2.75
    yaci:
      startBlockHash: 285f58fd09cbb95ac5ffd6f644f7907dfb3faff63155b8a86a9c7b0e99503397
      startSlotNumber: "103737886"
      network: main
      cardanoNodeHost: relays-new.cardano-mainnet.iohk.io
      cardanoNodePort: "3001"
      cardanoNodeProtocolMagic: "764824073"
    monitoring:
      alerting:
        enabled: false
    leaderboardForceResults: "true"
    corsAllowedOrigins: https://{{ .Values.domain }},https://cip1694.metadata.dev.cf-deployments.org,http://localhost:3000
    ingress:
      additionalDomains:
        - api.cip1694.metadata.dev.cf-deployments.org

cf-cardano-ballot-verification-api:
  enabled: true
  values:
    image:
      tag: 0.2.75
    springProfiles: prod
    corsAllowedOrigins: https://{{ .Values.domain }},https://cip1694.metadata.dev.cf-deployments.org,http://localhost:3000
    ingress:
      additionalDomains:
        - verification-api.cip1694.metadata.dev.cf-deployments.org

cf-cardano-ballot-ledger-follower-api:
  enabled: true
  values:
    image:
      tag: 0.2.75
    springProfiles: prod
    bindOnEventIds: CIP-1694_Pre_Ratification_TEST_2
    yaci:
      startBlockHash: 5fbd74e502832d31301b3473117cb99d162b3b0fc149656391f806170c93e1c0
      startSlotNumber: "106876819"
      network: main
      cardanoNodeHost: relays-new.cardano-mainnet.iohk.io
      cardanoNodePort: "3001"
      cardanoNodeProtocolMagic: "764824073"
    instances:
      - name: follower-1
        enabled: true
        schemaName: follower_1
      - name: follower-2
        enabled: true
        schemaName: follower_2
    corsAllowedOrigins: https://{{ .Values.domain }},https://cip1694.metadata.dev.cf-deployments.org,http://localhost:3000
    cardanoSnapshotBoundsCheckEnabled: "true"
    startupProbe:
      initialDelaySeconds: 0
      periodSeconds: 30
      failureThreshold: 20
    ingress:
      additionalDomains:
        - follower-api.cip1694.metadata.dev.cf-deployments.org

cf-voting-verification-ui:
  values:
    image:
      tag: 0.2.75

cf-vote-commitment:
  values:
    image:
      tag: 0.2.75
    springProfiles: prod
    instances:
      - name: active-hour
        voteCommitmentCronExpression: "0 00 * * * *"
      - name: active-half-hour
        voteCommitmentCronExpression: "0 30 * * * *"
    ledgerFollowerAppUrl: http://cf-cardano-ballot-ledger-follower-api-voting-ledger-follower-ap:9090
