stage: stg

network: preprod

domain: stg.cf-cip1694-preprod.eu-west-1.metadata.dev.cf-deployments.org

cf-cardano-ballot-infra:
  enabled: true

cf-cardano-ballot-ui:
  enabled: true
  values:
    image:
      tag: 0.2.75
    votingAppServerUrl: "https://api.cip1694.metadata.dev.cf-deployments.org"
    votingLedgerFollowerAppServerUrl: "https://follower-api.cip1694.metadata.dev.cf-deployments.org"
    votingVerificationAppServerUrl: "https://verification-api.cip1694.metadata.dev.cf-deployments.org"
    eventId: "CIP-1694_Pre_Ratification_B240"
    categoryId: "CIP-1694_Pre_Ratification_B240"
    googleGormUrl: "https://docs.google.com/forms/u/0/d/e/1FAIpQLSe-dSU0-bi8bjk0wiOaRXj02nxYLvgnpKBgc-eYGRpPYO-y5Q"
    googleFormVoteContextInputName: "entry.75173622"
    ingress:
      additionalDomains:
        - cip1694.metadata.dev.cf-deployments.org

cf-cardano-ballot-voting-api:
  enabled: true
  values:
    image:
      tag: v0.2.70-2-g51b6485d
    monitoring:
      alerting:
        enabled: false
    leaderboardForceResults: "true"
    corsAllowedOrigins: https://{{ .Values.domain }},https://cip1694.metadata.dev.cf-deployments.org,http://localhost:3000
    ingress:
      additionalDomains:
        - api.cip1694.metadata.dev.cf-deployments.org

cf-cardano-ballot-verification-api:
  enabled: true
  values:
    image:
      tag: 0.2.71
    corsAllowedOrigins: https://{{ .Values.domain }},https://cip1694.metadata.dev.cf-deployments.org,http://localhost:3000
    ingress:
      additionalDomains:
        - verification-api.cip1694.metadata.dev.cf-deployments.org

cf-cardano-ballot-ledger-follower-api:
  enabled: true
  values:
    image:
      tag: v0.2.70-2-g51b6485d
    bindOnEventIds: CIP-1694_Pre_Ratification_B240
    yaci:
      startBlockHash: ad03698d53d72b86b40c7747ffd5a960fbb3a71ac2f1189169e9d315449c24dc
      startSlotNumber: "41558438"
    instances:
      - name: follower-1
        enabled: true
        schemaName: follower_1
      - name: follower-2
        enabled: true
        schemaName: follower_2
    corsAllowedOrigins: https://{{ .Values.domain }},https://cip1694.metadata.dev.cf-deployments.org,http://localhost:3000
    ingress:
      additionalDomains:
        - follower-api.cip1694.metadata.dev.cf-deployments.org

cf-voting-verification-ui:
  values:
    image:
      tag: 0.2.71

cf-vote-commitment:
  values:
    image:
      tag: 0.2.71
    instances:
      - name: active-hour
        voteCommitmentCronExpression: "0 15 * * * *"
      - name: active-half-hour
        voteCommitmentCronExpression: "0 45 * * * *"
    ledgerFollowerAppUrl: http://cf-cardano-ballot-ledger-follower-api-voting-ledger-follower-ap:9090
