stage: dev

network: preprod

domain: dev.cf-summit-2023-preprod.eu-west-1.metadata.dev.cf-deployments.org

cf-summit-2023-infra:
  enabled: true
  postgresql:
    dbName: summit-2023

cf-summit-2023-ui:
  enabled: true
  values:
    frontendUrl: https://{{ .Values.domain }}
    votingAppServerUrl: https://api.dev.cf-summit-2023-preprod.eu-west-1.metadata.dev.cf-deployments.org
    votingLedgerFollowerAppServerUrl: https://follower-api.dev.cf-summit-2023-preprod.eu-west-1.metadata.dev.cf-deployments.org
    votingVerificationAppServerUrl: https://verification-api.dev.cf-summit-2023-preprod.eu-west-1.metadata.dev.cf-deployments.org
    userVerificationServerUrl: https://user-verification.dev.cf-summit-2023-preprod.eu-west-1.metadata.dev.cf-deployments.org
    targetNetwork: PREPROD
    eventId: CF_SUMMIT_2023_4BCC
    discordChannelUrl: https://discord.gg/XekFHYXNmu
    discordBotUrl: https://discord.com/channels/945974991718068254/1149627691310530570
    discordSupportChannelUrl: https://discord.gg/svAcdYjMXx
    image:
      tag: 0.2.64-23-ea838

cf-summit-2023-voting-api:
  enabled: true
  values:
    useJwt: true
    leaderboardForceResults: "true"
    instances:
      - name: passive
        active: "false"
        replicas: 2
      - name: active-hour
        active: "true"
        voteCommitmentCronExpression: "0 15 * * * *"
      - name: active-half-hour
        active: "true"
        voteCommitmentCronExpression: "0 45 * * * *"
    image:
      tag: 0.2.64-21-e16cb
    ledgerFollowerAppUrl: http://cf-summit-2023-ledger-follower-api-voting-ledger-follower-app:9090
    corsAllowedOrigins: https://{{ .Values.domain }},https://api.{{ .Values.domain }},http://localhost:3000
    monitoring:
      alerting:
        enabled: false

cf-summit-2023-verification-api:
  enabled: true
  values:
    image:
      tag: 0.2.67
    ledgerFollowerAppUrl: http://cf-summit-2023-ledger-follower-api-voting-ledger-follower-app:9090
    corsAllowedOrigins: https://{{ .Values.domain }},http://localhost:3000

cf-user-verification-service:
  enabled: true
  values:
    image:
      tag: 0.2.67
    discordBotEventIdBinding: CF_SUMMIT_2023_4BCC
    ledgerFollowerAppUrl: http://cf-summit-2023-ledger-follower-api-voting-ledger-follower-app:9090
    corsAllowedOrigins: https://{{ .Values.domain }},http://localhost:3000

cf-summit-2023-ledger-follower-api:
  enabled: true
  values:
    image:
      tag: 0.2.67
    bindOnEventIds: CF_SUMMIT_2023_4BCC
    yaci:
      startBlockHash: e575e717f19ed8e4a21af879577f58bfe9a76e0501470866fc9866323376fd2d
      startSlotNumber: "41335078"
    corsAllowedOrigins: https://{{ .Values.domain }},http://localhost:3000
    instances:
      - name: follower-1
        enabled: true
#        imageTag: 0.2.36
        schemaName: follower_1
      - name: follower-2
        enabled: true
#        imageTag: 0.2.36
        schemaName: follower_2

cf-discord-wallet-verification-bot:
  enabled: true
  values:
    image:
      tag: 11f6f15
    backendBaseUrl: https://user-verification.{{ .Values.domain }}
    frontendUrl: https://{{ .Values.domain }}
    diagnosticMode:
      enabled: false
