name: Build and Publish Docker images

on:
  push:
    branches: [ main, develop ]
    tags:
      - '[0-9]+.[0-9]+.[0-9]+*'
  pull_request:
    types: [ opened, synchronize ]
  workflow_dispatch:

env:
  PRIVATE_DOCKER_REGISTRY_URL: ${{ secrets.GITLAB_DOCKER_REGISTRY_URL }}
  PRIVATE_DOCKER_REGISTRY_USER: Deploy-Token
  PRIVATE_DOCKER_REGISTRY_PASS: ${{ secrets.GITLAB_PKG_REGISTRY_TOKEN }}
  DOCKER_PUSH: false

jobs:

  voting-app:
    runs-on: ${{ fromJson(vars.RUNS_ON) }}
    env:
      APP_NAME: voting-app
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: ⛮ cf-gha-baseline
        uses: cardanofoundation/cf-gha-workflows/./actions/cf-gha-baseline@main
        with:
          working-directory: ./backend-services/${{ env.APP_NAME }}
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          PRIVATE_DOCKER_REGISTRY_URL: ${{ env.PRIVATE_DOCKER_REGISTRY_URL }}
          PRIVATE_DOCKER_REGISTRY_USER: ${{ env.PRIVATE_DOCKER_REGISTRY_USER }}
          PRIVATE_DOCKER_REGISTRY_PASS: ${{ env.PRIVATE_DOCKER_REGISTRY_PASS }}
          HUB_DOCKER_COM_USER: ${{ secrets.HUB_DOCKER_COM_USER }}
          HUB_DOCKER_COM_PASS: ${{ secrets.HUB_DOCKER_COM_PASS }}
          DOCKER_REGISTRIES: "${{ secrets.DOCKER_REGISTRIES }}"

      - name:  🌍 earthly (docker build and push)
        run: |
          earthly +${{ env.APP_NAME }} \
            --PUSH=${DOCKER_PUSH} \
            --DOCKER_REGISTRIES="${{ secrets.DOCKER_REGISTRIES }}" \
            --DOCKER_IMAGES_EXTRA_TAGS="${EARTHLY_DOCKER_IMAGES_EXTRA_TAGS}"

  voting-commitment-app:
    runs-on: ${{ fromJson(vars.RUNS_ON) }}
    env:
      APP_NAME: vote-commitment-app
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: ⛮ cf-gha-baseline
        uses: cardanofoundation/cf-gha-workflows/./actions/cf-gha-baseline@main
        working-directory: ./backend-services/${{ env.APP_NAME }}
        with:
          working-directory: ./backend-services/${{ env.APP_NAME }}
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          PRIVATE_DOCKER_REGISTRY_URL: ${{ env.PRIVATE_DOCKER_REGISTRY_URL }}
          PRIVATE_DOCKER_REGISTRY_USER: ${{ env.PRIVATE_DOCKER_REGISTRY_USER }}
          PRIVATE_DOCKER_REGISTRY_PASS: ${{ env.PRIVATE_DOCKER_REGISTRY_PASS }}
          HUB_DOCKER_COM_USER: ${{ secrets.HUB_DOCKER_COM_USER }}
          HUB_DOCKER_COM_PASS: ${{ secrets.HUB_DOCKER_COM_PASS }}
          DOCKER_REGISTRIES: "${{ secrets.DOCKER_REGISTRIES }}"

      - name:  🌍 earthly (docker build and push)
        run: |
          earthly +${{ env.APP_NAME }} \
            --PUSH=${DOCKER_PUSH} \
            --DOCKER_REGISTRIES="${{ secrets.DOCKER_REGISTRIES }}" \
            --DOCKER_IMAGES_EXTRA_TAGS="${EARTHLY_DOCKER_IMAGES_EXTRA_TAGS}"
  

  voting-ledger-follower-app:
    runs-on: ${{ fromJson(vars.RUNS_ON) }}
    env:
      APP_NAME: voting-ledger-follower-app
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: ⛮ cf-gha-baseline
        uses: cardanofoundation/cf-gha-workflows/./actions/cf-gha-baseline@main
        with:
          working-directory: ./backend-services/${{ env.APP_NAME }}
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          PRIVATE_DOCKER_REGISTRY_URL: ${{ env.PRIVATE_DOCKER_REGISTRY_URL }}
          PRIVATE_DOCKER_REGISTRY_USER: ${{ env.PRIVATE_DOCKER_REGISTRY_USER }}
          PRIVATE_DOCKER_REGISTRY_PASS: ${{ env.PRIVATE_DOCKER_REGISTRY_PASS }}
          HUB_DOCKER_COM_USER: ${{ secrets.HUB_DOCKER_COM_USER }}
          HUB_DOCKER_COM_PASS: ${{ secrets.HUB_DOCKER_COM_PASS }}
          DOCKER_REGISTRIES: "${{ secrets.DOCKER_REGISTRIES }}"

      - name:  🌍 earthly (docker build and push)
        run: |
          earthly +${{ env.APP_NAME }} \
            --PUSH=${DOCKER_PUSH} \
            --DOCKER_REGISTRIES="${{ secrets.DOCKER_REGISTRIES }}" \
            --DOCKER_IMAGES_EXTRA_TAGS="${EARTHLY_DOCKER_IMAGES_EXTRA_TAGS}"

  voting-verification-app:
    runs-on: ${{ fromJson(vars.RUNS_ON) }}
    env:
      APP_NAME: voting-verification-app
    needs: build-version
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: ⛮ cf-gha-baseline
        uses: cardanofoundation/cf-gha-workflows/./actions/cf-gha-baseline@main
        with:
          working-directory: ./backend-services/${{ env.APP_NAME }}
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          PRIVATE_DOCKER_REGISTRY_URL: ${{ env.PRIVATE_DOCKER_REGISTRY_URL }}
          PRIVATE_DOCKER_REGISTRY_USER: ${{ env.PRIVATE_DOCKER_REGISTRY_USER }}
          PRIVATE_DOCKER_REGISTRY_PASS: ${{ env.PRIVATE_DOCKER_REGISTRY_PASS }}
          HUB_DOCKER_COM_USER: ${{ secrets.HUB_DOCKER_COM_USER }}
          HUB_DOCKER_COM_PASS: ${{ secrets.HUB_DOCKER_COM_PASS }}
          DOCKER_REGISTRIES: "${{ secrets.DOCKER_REGISTRIES }}"

      - name:  🌍 earthly (docker build and push)
        run: |
          earthly +${{ env.APP_NAME }} \
            --PUSH=${DOCKER_PUSH} \
            --DOCKER_REGISTRIES="${{ secrets.DOCKER_REGISTRIES }}" \
            --DOCKER_IMAGES_EXTRA_TAGS="${EARTHLY_DOCKER_IMAGES_EXTRA_TAGS}"

  user-verification-service:
    runs-on: ${{ fromJson(vars.RUNS_ON) }}
    env:
      APP_NAME: user-verification-service
    needs: build-version
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: ⛮ cf-gha-baseline
        uses: cardanofoundation/cf-gha-workflows/./actions/cf-gha-baseline@main
        with:
          working-directory: ./backend-services/${{ env.APP_NAME }}
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          PRIVATE_DOCKER_REGISTRY_URL: ${{ env.PRIVATE_DOCKER_REGISTRY_URL }}
          PRIVATE_DOCKER_REGISTRY_USER: ${{ env.PRIVATE_DOCKER_REGISTRY_USER }}
          PRIVATE_DOCKER_REGISTRY_PASS: ${{ env.PRIVATE_DOCKER_REGISTRY_PASS }}
          HUB_DOCKER_COM_USER: ${{ secrets.HUB_DOCKER_COM_USER }}
          HUB_DOCKER_COM_PASS: ${{ secrets.HUB_DOCKER_COM_PASS }}
          DOCKER_REGISTRIES: "${{ secrets.DOCKER_REGISTRIES }}"

      - name:  🌍 earthly (docker build and push)
        run: |
          earthly +${{ env.APP_NAME }} \
            --PUSH=${DOCKER_PUSH} \
            --DOCKER_REGISTRIES="${{ secrets.DOCKER_REGISTRIES }}" \
            --DOCKER_IMAGES_EXTRA_TAGS="${EARTHLY_DOCKER_IMAGES_EXTRA_TAGS}"

  ui-summit-2024:
    runs-on: ${{ fromJson(vars.RUNS_ON) }}
    env:
      APP_NAME: ui-summit-2024
    needs: build-version
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: ⛮ cf-gha-baseline
        uses: cardanofoundation/cf-gha-workflows/./actions/cf-gha-baseline@main
        with:
          working-directory: ./backend-services/${{ env.APP_NAME }}
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          PRIVATE_DOCKER_REGISTRY_URL: ${{ env.PRIVATE_DOCKER_REGISTRY_URL }}
          PRIVATE_DOCKER_REGISTRY_USER: ${{ env.PRIVATE_DOCKER_REGISTRY_USER }}
          PRIVATE_DOCKER_REGISTRY_PASS: ${{ env.PRIVATE_DOCKER_REGISTRY_PASS }}
          HUB_DOCKER_COM_USER: ${{ secrets.HUB_DOCKER_COM_USER }}
          HUB_DOCKER_COM_PASS: ${{ secrets.HUB_DOCKER_COM_PASS }}
          DOCKER_REGISTRIES: "${{ secrets.DOCKER_REGISTRIES }}"

      - name:  🌍 earthly (docker build and push)
        run: |
          earthly +${{ env.APP_NAME }} \
            --PUSH=${DOCKER_PUSH} \
            --DOCKER_REGISTRIES="${{ secrets.DOCKER_REGISTRIES }}" \
            --DOCKER_IMAGES_EXTRA_TAGS="${EARTHLY_DOCKER_IMAGES_EXTRA_TAGS}"

  admin-cli:
    runs-on: ${{ fromJson(vars.RUNS_ON) }}
    env:
      APP_NAME: voting-admin-app
    needs: build-version
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: ⛮ cf-gha-baseline
        uses: cardanofoundation/cf-gha-workflows/./actions/cf-gha-baseline@main
        with:
          working-directory: ./backend-services/${{ env.APP_NAME }}
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          PRIVATE_DOCKER_REGISTRY_URL: ${{ env.PRIVATE_DOCKER_REGISTRY_URL }}
          PRIVATE_DOCKER_REGISTRY_USER: ${{ env.PRIVATE_DOCKER_REGISTRY_USER }}
          PRIVATE_DOCKER_REGISTRY_PASS: ${{ env.PRIVATE_DOCKER_REGISTRY_PASS }}
          HUB_DOCKER_COM_USER: ${{ secrets.HUB_DOCKER_COM_USER }}
          HUB_DOCKER_COM_PASS: ${{ secrets.HUB_DOCKER_COM_PASS }}
          DOCKER_REGISTRIES: "${{ secrets.DOCKER_REGISTRIES }}"

      - name:  🌍 earthly (docker build and push)
        run: |
          earthly +${{ env.APP_NAME }} \
            --PUSH=${DOCKER_PUSH} \
            --DOCKER_REGISTRIES="${{ secrets.DOCKER_REGISTRIES }}" \
            --DOCKER_IMAGES_EXTRA_TAGS="${EARTHLY_DOCKER_IMAGES_EXTRA_TAGS}"
