name: Build and Publish Docker images

on:
  push:
    branches: [ main, develop ]
    tags:
      - '[0-9]+.[0-9]+.[0-9]+*'
  pull_request:
    types: [ opened, synchronize ]
  workflow_dispatch:

env:
  PRIVATE_DOCKER_REGISTRY_URL: ${{ secrets.GITLAB_DOCKER_REGISTRY_URL }}
  PRIVATE_DOCKER_REGISTRY_USER: Deploy-Token
  PRIVATE_DOCKER_REGISTRY_PASS: ${{ secrets.GITLAB_PKG_REGISTRY_TOKEN }}
  DOCKER_PUSH: true

jobs:

  backend-services:
    runs-on: ${{ fromJson(vars.RUNS_ON) }}
    strategy:
      matrix:
        service:
          - voting-app
          - vote-commitment-app
          - voting-ledger-follower-app
          - voting-verification-app
          - user-verification-service
          - voting-admin-app
          - keri-ballot-verifier
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: ⛮ cf-gha-baseline
        uses: cardano-foundation/cf-gha-workflows/./actions/cf-gha-baseline@main
        id: cf-gha-baseline
        with:
          working-directory: ./backend-services/${{ matrix.service }}
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          PRIVATE_DOCKER_REGISTRY_URL: ${{ env.PRIVATE_DOCKER_REGISTRY_URL }}
          PRIVATE_DOCKER_REGISTRY_USER: ${{ env.PRIVATE_DOCKER_REGISTRY_USER }}
          PRIVATE_DOCKER_REGISTRY_PASS: ${{ env.PRIVATE_DOCKER_REGISTRY_PASS }}
          HUB_DOCKER_COM_USER: ${{ secrets.HUB_DOCKER_COM_USER }}
          HUB_DOCKER_COM_PASS: ${{ secrets.HUB_DOCKER_COM_PASS }}
          DOCKER_REGISTRIES: "${{ secrets.DOCKER_REGISTRIES }}"

      - name:  🌍 earthly (docker build and push)
        run: |
          earthly +${{ matrix.service }} \
            --PUSH=${DOCKER_PUSH} \
            --DOCKER_REGISTRIES="${{ secrets.DOCKER_REGISTRIES }}" \
            --DOCKER_IMAGES_EXTRA_TAGS="${EARTHLY_DOCKER_IMAGES_EXTRA_TAGS}"

  ui-summit-2024:
    runs-on: ${{ fromJson(vars.RUNS_ON) }}
    env:
      APP_NAME: ui-summit-2024
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: ⛮ cf-gha-baseline
        uses: cardano-foundation/cf-gha-workflows/./actions/cf-gha-baseline@main
        id: cf-gha-baseline
        with:
          working-directory: ./ui/summit-2024
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          PRIVATE_DOCKER_REGISTRY_URL: ${{ env.PRIVATE_DOCKER_REGISTRY_URL }}
          PRIVATE_DOCKER_REGISTRY_USER: ${{ env.PRIVATE_DOCKER_REGISTRY_USER }}
          PRIVATE_DOCKER_REGISTRY_PASS: ${{ env.PRIVATE_DOCKER_REGISTRY_PASS }}
          HUB_DOCKER_COM_USER: ${{ secrets.HUB_DOCKER_COM_USER }}
          HUB_DOCKER_COM_PASS: ${{ secrets.HUB_DOCKER_COM_PASS }}
          DOCKER_REGISTRIES: "${{ secrets.DOCKER_REGISTRIES }}"

      - name:  🌍 earthly (docker build and push)
        run: |
          earthly +${{ env.APP_NAME }} \
            --VITE_VERSION=${{ steps.cf-gha-baseline.outputs.GIT_SHORT_COMMIT }} \
            --PUSH=${DOCKER_PUSH} \
            --DOCKER_REGISTRIES="${{ secrets.DOCKER_REGISTRIES }}" \
            --DOCKER_IMAGES_EXTRA_TAGS="${EARTHLY_DOCKER_IMAGES_EXTRA_TAGS}"

  dispatch-build-success-event:
    runs-on: ${{ fromJson(vars.RUNS_ON) }}
    needs:
      - ui-summit-2024
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: ⛮ cf-gha-baseline
        uses: cardano-foundation/cf-gha-workflows/./actions/cf-gha-baseline@main
        id: cf-gha-baseline
        with:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          PRIVATE_DOCKER_REGISTRY_URL: ${{ env.PRIVATE_DOCKER_REGISTRY_URL }}
          PRIVATE_DOCKER_REGISTRY_USER: ${{ env.PRIVATE_DOCKER_REGISTRY_USER }}
          PRIVATE_DOCKER_REGISTRY_PASS: ${{ env.PRIVATE_DOCKER_REGISTRY_PASS }}
          HUB_DOCKER_COM_USER: ${{ secrets.HUB_DOCKER_COM_USER }}
          HUB_DOCKER_COM_PASS: ${{ secrets.HUB_DOCKER_COM_PASS }}
          DOCKER_REGISTRIES: "${{ secrets.DOCKER_REGISTRIES }}"

      - name: Dispatch successful build event to private repo
        uses: cardano-foundation/cf-gha-workflows/./actions/cf-gha-dispatch-event@main
        with:
          EVENT_TYPE: "${{ github.event_name }}-${{ steps.cf-gha-baseline.outputs.TRIGGERING_REF }}-${{ steps.cf-gha-baseline.outputs.BRANCH_NAME }}"
          GITHUB_TOKEN: ${{ secrets.PRIVATE_REPO_PAT }}
          GITHUB_REPO: ${{ secrets.PRIVATE_REPO }}
          TRIGGERING_EVENT: ${{ github.event_name }}
          TRIGGERING_REF: ${{ steps.cf-gha-baseline.outputs.TRIGGERING_REF }}
          TRIGGERING_BRANCH: ${{ steps.cf-gha-baseline.outputs.BRANCH_NAME }}
          TRIGGERING_GHRUNID: ${{ github.run_id }}
          GIT_SHORT_COMMIT: ${{ steps.cf-gha-baseline.outputs.GIT_SHORT_COMMIT }}
