name: Run Tests

on:
  push:
    branches: [ main, develop ]
    tags:
      - '[0-9]+.[0-9]+.[0-9]+*'
  pull_request:
    types: [ opened, synchronize ]
  workflow_dispatch:

jobs:
  test:
    runs-on: self-hosted
    strategy:
      matrix:
        service: ['user-verification-service', 'voting-app', 'voting-ledger-follower-app']        
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Check if there were changes for the service
        id: metadata
        run: |
          if [[ "${{ github.event_name }}" == "pull_request" ]] \
          || [[ "${{ github.event_name }}" == "push" ]] 
          then
            if git log --pretty=format:'%h' -n 1 backend-services/${{ matrix.service }} | grep -q ${{ github.sha }} 
            then
              echo "SERVICE_CHANGED=true" | tee -a "$GITHUB_OUTPUT"
            else
              echo "SERVICE_CHANGED=false" | tee -a "$GITHUB_OUTPUT"
            fi
          else # if the event is not a push or pull_request, then we assume that the service has changed
            echo "SERVICE_CHANGED=true" | tee -a "$GITHUB_OUTPUT"
          fi

      - name: Setup JDK 21
        if: steps.metadata.outputs.SERVICE_CHANGED == true
        uses: actions/setup-java@v3
        with:
          java-version: '21'
          distribution: 'corretto'
          cache: gradle

      - name: Run tests
        if: steps.metadata.outputs.SERVICE_CHANGED == true
        working-directory: ./backend-services/${{ matrix.service }}
        run: ./gradlew test
          
      - name: Generate JaCoCo Badge
        if: steps.metadata.outputs.SERVICE_CHANGED == true
        uses: cicirello/jacoco-badge-generator@v2
        with:
          generate-branches-badge: true
          badges-directory: ./backend-services/${{ matrix.service }}/build/reports/jacoco/test/html/badges
          jacoco-csv-file: ./backend-services/${{ matrix.service }}/build/reports/jacoco/test/jacocoTestReport.csv

      - name: Log coverage percentage
        if: steps.metadata.outputs.SERVICE_CHANGED == true
        run: |
          echo "coverage = ${{ steps.jacoco.outputs.coverage }}"
          echo "branch coverage = ${{ steps.jacoco.outputs.branches }}"

      - name: Publish coverage report to GitHub Pages
        uses: JamesIves/github-pages-deploy-action@v4
        if: github.ref == 'refs/heads/main' 
        with:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          BRANCH: gh-pages
          folder: ./backend-services/${{ matrix.service }}/build/reports/jacoco/test/html
          target-folder: ${{ matrix.service }}/coverage-report/
